apiVersion: dapr.io/v1alpha1
#apiVersion: 1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    timeouts:
      general: 600s

    retries:
      # retry policy definitions
      retry3Times:
        policy: exponential
        maxInterval: 15s
        maxRetries: 3 # Retry indefinitely

  targets:
    apps:
      # apps and their applied policies here
      api-gateway:
        timeout: general
      goat-service:
        timeout: general
        retry: retry3Times
      code-executor:
        timeout: general
