apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goatswitch-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.goatswitch.ai
        - demo.goatswitch.ai
      secretName: letsencrypt-prod
  rules:
    - host: api.goatswitch.ai
      http:
        paths:
          - backend:
              service:
                name: api-gateway
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: demo.goatswitch.ai
      http:
        paths:
          - backend:
              service:
                name: api-gateway
                port:
                  number: 80
            path: /
            pathType: Prefix
