# Routes the traces from pods to the otel-collector
# Always uses the local node's otel-collector
apiVersion: v1
kind: Service
metadata:
  name: otlp-router
  namespace: dapr-monitoring
  labels:
    app: otel-router
spec:
  internalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: otel-collector
  ports:
    - name: grpc
      port: 4317
---
# Routes the traces from pods to the otel-collector
# Windows cannot run the otel-collector, so we need to route the traces to a Linux node
apiVersion: v1
kind: Service
metadata:
  name: otlp-win-router
  namespace: dapr-monitoring
  labels:
    app: otel-win-router
spec:
  internalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/instance: otel-collector
  ports:
    - name: grpc
      port: 4317
