apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-service
  labels:
    app: goat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-service
  template:
    metadata:
      labels:
        app: goat-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "goat-service"
        dapr.io/enable-api-logging: "true"
        dapr.io/app-port: "4999"
        dapr.io/app-protocol: "grpc"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
    spec:
      containers:
        - name: goat-service
          image: goatswitch_goat_service:latest
          imagePullPolicy: Never
